[versions]
agp = "8.13.1"
kotlin = "2.2.21"
omniPlugin = "0.4.5"

composeBom = "2025.11.01"
coreKtx = "1.17.0"
activityCompose = "1.11.0"
navigationCompose = "2.9.6"
lifecycle = "2.9.4"
materialComponents = "1.13.0"
multidex = "1.0.3"

# ... existing code ...
junit4 = "4.13.2"
kotest = "6.0.5"
androidxTestExtJunit = "1.3.0"
espressoCore = "3.7.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material = { module = "androidx.compose.material:material" }
compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

google-material = { module = "com.google.android.material:material", version.ref = "materialComponents" }
support-multidex = { module = "com.android.support:multidex", version.ref = "multidex" }

junit4 = { module = "junit:junit", version.ref = "junit4" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }

androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtJunit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
omni = { id = "org.jesperancinha.plugins.omni", version.ref = "omniPlugin" }
jacoco = { id = "jacoco" } # uses Gradle-provided version

[bundles]
compose = [
    "compose-ui",
    "compose-ui-graphics",
    "compose-ui-tooling-preview",
    "compose-material",
    "compose-material3"
]
compose-debug = [
    "compose-ui-tooling",
    "compose-ui-test-manifest"
]
compose-test = [
    "compose-ui-test-junit4"
]
androidx-test = [
    "androidx-test-ext-junit",
    "androidx-test-espresso-core"
]