name: matrix-anywhere-android-pull_request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

#    - name: Set up Android 30
#      uses: jesperancinhaorg/android-action@v0.0.3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Creates properties
      run: touch local.properties

#    - name: Start emulator
#      run: make start-emulator-linux-no-window &
#
#    - name: Instumentation tests
#      run: make run-android-instrumentation

    - name: Download Android dependencies
      run: make dependencies

    - name: Gradle Lint Test
      run: make lint

    - name: Build with Gradle
      run: ./gradlew build
